linters-settings:
  funlen:
    lines: 160
    statements: 72
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tiendc/gofn)
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  lll:
    line-length: 120
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - contextcheck
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
