name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: build
        run: make build

      - name: test
        run: make test
